CXX = g++
CXXFLAGS = -Wall -std=c++17

build: main.cpp sentence_tokenizer.cpp word_tokenizer.cpp lemmatizer.cpp
	$(CXX) $(CXXFLAGS) main.cpp sentence_tokenizer.cpp word_tokenizer.cpp lemmatizer.cpp -o nlp 

