#pragma once

#include "stella/components/animation_player.hpp"
#include "stella/components/body2d.hpp"
#include "stella/components/camera.hpp"
#include "stella/components/character_animation.hpp"
#include "stella/components/charcode.hpp"
#include "stella/components/color.hpp"
#include "stella/components/dimension.hpp"
#include "stella/components/layer.hpp"
#include "stella/components/npc.hpp"
#include "stella/components/position.hpp"
#include "stella/components/script.hpp"
#include "stella/components/shape.hpp"
#include "stella/components/speech_container.hpp"
#include "stella/components/sprite_group.hpp"
#include "stella/components/sprite.hpp"
#include "stella/components/text.hpp"
#include "stella/components/tile.hpp"
#include "stella/components/timer.hpp"
#include "stella/components/typewriter.hpp"

// TODO: Add widgets for the following new components
#include "stella/components/transform.hpp"
#include "stella/components/in_group.hpp"
