#pragma once

#include "stella/systems/animation_system.h"
#include "stella/systems/physics_system.h"
#include "stella/systems/particle_system.h"
#include "stella/systems/player_system.h"
#include "stella/systems/render_system.h"
#include "stella/systems/scroll_system.h"
#include "stella/systems/tiled_scroll_system.h"
#include "stella/systems/transform_system.h"
#include "stella/systems/movement_system.h"
#include "stella/systems/tile_system.h"
#include "stella/systems/text_system.h"
#include "stella/systems/bitmap_text_system.h"
#include "stella/systems/color_system.h"
#include "stella/systems/timer_system.h"
#include "stella/systems/speech_system.h"
