#pragma once

#include "stella/systems/animation.h"
#include "stella/systems/character_animation.h"
#include "stella/systems/color.h"
#include "stella/systems/movement.h"
#include "stella/systems/npc.h"
#include "stella/systems/particle.h"
#include "stella/systems/physics.h"
//#include "stella/systems/player.h"
#include "stella/systems/render.h"
#include "stella/systems/scroll.h"
#include "stella/systems/speech.h"
#include "stella/systems/text.h"
#include "stella/systems/tile.h"
#include "stella/systems/tiled_scroll.h"
#include "stella/systems/timer.h"
#include "stella/systems/transform.h"
